package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.python
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'ExcelSheet_Build'
in the project with id = 'ExcelSheet', and delete the patch script.
*/
create(RelativeId("ExcelSheet"), BuildType({
    id("ExcelSheet_Build")
    name = "Build"

    vcs {
        root(RelativeId("ExcelSheet_HttpsGithubComAjayKumar9375ExcelSheetGitRefsHeadsMain"))
    }

    steps {
        python {
            id = "python_runner"
            command = file {
                filename = "excel_Py_Script.py"
                scriptArguments = """--directory "Book1.xlsx""""
            }
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

