package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.notifications
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'feature_1'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("feature_1")) {
    features {
        add {
            notifications {
                enabled = false
                notifierSettings = emailNotifier {
                    email = "ajay.kumar@kpit.com"
                }
                buildFailed = true
                buildFinishedSuccessfully = true
            }
        }
    }
}
