// package patches.buildTypes

<<<<<<< HEAD
// import jetbrains.buildServer.configs.kotlin.*
// import jetbrains.buildServer.configs.kotlin.buildSteps.PythonBuildStep
// import jetbrains.buildServer.configs.kotlin.buildSteps.python
// import jetbrains.buildServer.configs.kotlin.ui.*
=======
import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.python
import jetbrains.buildServer.configs.kotlin.ui.*
>>>>>>> a0ebd134234121805164c7b4352d413ba9ad5e32

// /*
// This patch script was generated by TeamCity on settings change in UI.
// To apply the patch, change the buildType with id = 'feature_2'
// accordingly, and delete the patch script.
// */
// changeBuildType(RelativeId("feature_2")) {
//     params {
//         remove {
//             param("source", "json_source.json")
//         }
//     }

<<<<<<< HEAD
//     expectSteps {
//         python {
//             id = "python_runner"
//             command = file {
//                 filename = "main.py"
//                 scriptArguments = "--path_to_source_json_file %source% --path_to_destination_json_file %destination% --location_one %location1% --location_two %location2%"
//             }
//         }
//     }
//     steps {
//         update<PythonBuildStep>(0) {
//             enabled = false
//             clearConditions()
//         }
//         insert(1) {
//             step {
//                 id = "DslTesting_Feature1"
//                 type = "DslTesting_Feature1"
//                 executionMode = BuildStep.ExecutionMode.DEFAULT
//                 param("Organization", "KPIT")
//                 param("destination", "json_destination.json")
//                 param("location1", "PlantModel")
//                 param("location2", "Bsc")
//                 param("teamcity.step.phase", "")
//                 param("source", "json_source.json")
//             }
//         }
//     }
// }
=======
    expectSteps {
        python {
            id = "python_runner"
            command = file {
                filename = "main.py"
                scriptArguments = "--path_to_source_json_file %source% --path_to_destination_json_file %destination% --location_one %location1% --location_two %location2%"
            }
        }
    }
    steps {
        insert(1) {
            step {
                id = "DslTesting_Feature1"
                type = "DslTesting_Feature1"
                enabled = false
                executionMode = BuildStep.ExecutionMode.DEFAULT
                param("Organization", "KPIT")
                param("destination", "json_destination.json")
                param("location1", "PlantModel")
                param("location2", "Bsc")
                param("teamcity.step.phase", "")
                param("source", "json_source.json")
            }
        }
    }
}
>>>>>>> a0ebd134234121805164c7b4352d413ba9ad5e32
