package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'ZipingLocalDirectory_LocalDir'
in the project with id = 'ZipingLocalDirectory', and delete the patch script.
*/
create(RelativeId("ZipingLocalDirectory"), BuildType({
    id("ZipingLocalDirectory_LocalDir")
    name = "local_dir"

    steps {
        script {
            id = "simpleRunner"
            scriptContent = """zip -r archive_name.zip D:\Class_7\Our_Environment\*"""
        }
    }
}))

