package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'ExcelSheet_HttpsGithubComAjayKumar9375ExcelSheetGitRefsHeadsMain'
in the project with id = 'ExcelSheet', and delete the patch script.
*/
create(RelativeId("ExcelSheet"), GitVcsRoot({
    id("ExcelSheet_HttpsGithubComAjayKumar9375ExcelSheetGitRefsHeadsMain")
    name = "https://github.com/AjayKumar9375/Excel_sheet.git#refs/heads/main"
    url = "https://github.com/AjayKumar9375/Excel_sheet.git"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
}))

